#!/bin/sh

set -eu

uci -q batch <<'EOF'
set lpac.global=global
set lpac.global.apdu_backend='uqmi'
set lpac.global.http_backend='curl'
set lpac.global.apdu_debug='0'
set lpac.global.http_debug='0'
set lpac.global.custom_isd_r_aid='A0000005591010FFFFFFFF8900000100'
set lpac.at=at
set lpac.at.device='/dev/ttyUSB2'
set lpac.at.debug='0'
set lpac.uqmi=uqmi
set lpac.uqmi.device='/dev/cdc-wdm0'
set lpac.uqmi.debug='0'
set lpac.mbim=mbim
set lpac.mbim.device='/dev/cdc-wdm0'
set lpac.mbim.proxy='1'
commit lpac
EOF

exit 0
