#!/bin/sh

# WiFi: enable radios, bridge to lan, set SSIDs and password
uci set wireless.default_radio0.disabled=0
uci set wireless.default_radio0.network=lan
uci set wireless.default_radio0.ssid=openwrt_5g
uci set wireless.default_radio0.encryption=psk2
uci set wireless.default_radio0.key=12345678

uci set wireless.default_radio1.disabled=0
uci set wireless.default_radio1.network=lan
uci set wireless.default_radio1.ssid=openwrt
uci set wireless.default_radio1.encryption=psk2
uci set wireless.default_radio1.key=12345678

uci commit wireless

# LTE modem: Quectel EM060K-GL via QMI (uqmi)
uci set network.lan.ipaddr=192.168.201.1
uci set network.lan.netmask=255.255.255.0

uci set network.wan=interface
uci set network.wan.proto=qmi
uci set network.wan.device=/dev/cdc-wdm0
uci set network.wan.pdptype=ip
uci set network.wan.auth=none
uci set network.wan.roaming=1
uci set network.wan.apn=globaldata

uci commit network

# Firewall: replace anonymous defaults with explicit named zones
while uci -q delete firewall.@forwarding[0]; do :; done
while uci -q delete firewall.@zone[0]; do :; done

uci set firewall.lan=zone
uci set firewall.lan.name=lan
uci set firewall.lan.input=ACCEPT
uci set firewall.lan.output=ACCEPT
uci set firewall.lan.forward=ACCEPT
uci add_list firewall.lan.network=lan

uci set firewall.wan=zone
uci set firewall.wan.name=wan
uci set firewall.wan.input=REJECT
uci set firewall.wan.output=ACCEPT
uci set firewall.wan.forward=REJECT
uci set firewall.wan.masq=1
uci set firewall.wan.mtu_fix=1
uci add_list firewall.wan.network=wan

uci set firewall.lan_wan=forwarding
uci set firewall.lan_wan.src=lan
uci set firewall.lan_wan.dest=wan

uci commit firewall

exit 0
