#!/bin/sh

vpn_interface="$(uci -q get mcu.global.vpn_interface)"
[ -n "$vpn_interface" ] || vpn_interface=awg0
[ "$INTERFACE" = "$vpn_interface" ] || exit 0

case "$ACTION" in
	ifup)
		/usr/bin/vpn-switch sync
		;;
	ifdown)
		/usr/bin/vpn-switch wan
		;;
esac
